vscode:
  extensions:
    - ms-vscode.cmake-tools@1.4.2:85XiRZZTNCh6JgvEqefqww==
    - llvm-vs-code-extensions.vscode-clangd@0.1.7:drODQ7O13QYFp9Ufy1Plaw==
    - matepek.vscode-catch2-test-adapter@3.4.2:8HmPtYNiX6FRr+lAV/hQOQ==
    - twxs.cmake@0.0.17:aQNzlYa74rJFJ5/BnUF1yA==

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
    addLabel: true
