name: validate

on: [push, pull_request]

jobs:
  win64-complete:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools\validate.bat win64
  linux-complete:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh linux full
  win32-client:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools\validate.bat win32
  android-arm-client:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh android
  android-arm64-client:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh android-arm64
  android-x86-client:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh android-x86
  web-client:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh web
  mac-client:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh mac
  ios-client:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh ios
  unit-tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: BuildTools/validate.sh linux unit-tests
  code-coverage:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: BuildTools/validate.sh linux code-coverage
  check-formatting:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: ./Source
        clangFormatVersion: 9
